# This is a basic workflow to help you get started with Actions
name: Pipeline
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
    - Chapter15/**
    - .github/workflows/pipeline.yaml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Env to set reusable variables
env:
  RGNAME: rgcicd4aksaug8
  ACRNAME: acr4aksaug8
  AKSNAME: aks4cicdaug8
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 3  jobs called Platform,Build and Deploy

  Deploy:
    runs-on: ubuntu-latest
#    needs: Build
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: az account set
        run: az account set --subscription 30d0d4bc-0d65-4a43-a555-e496121a6f2e
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: rgcicd4aksaug8
          cluster-name: aks4cicdaug8

      - name: Helm upgrade
        run: |
          helm upgrade website Chapter15/website --install \
            --set image.repository=$ACRNAME.azurecr.io/website/website \
            --set image.tag=${{ github.run_number }}
      - name: Get service IP
        run: |
          PUBLICIP=""
          while [ -z $PUBLICIP ]; do
            echo "Waiting for public IP..."
            PUBLICIP=$(kubectl get service website -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            [ -z "$PUBLICIP" ] && sleep 10
          done
          echo $PUBLICIP
