# This is a basic workflow to help you get started with Actions
name: Pipeline
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
    - Chapter15/**
    - .github/workflows/pipeline.yaml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Env to set reusable variables
#env:
#  ACRNAME: ACRforAKSAug
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 3  jobs called Platform,Build and Deploy
  Platform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2

      - name: az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Az RG Create
        run: az group create --name CICDAKS-RG-TEST313 -l eastus
